import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/');
  await page.goto('http://localhost:4200/login');
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('donnie@gmail.com');
  await page.getByText('Employee').click();
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('A');
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('Azoff.1');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('div').filter({ hasText: /^Securities$/ }).first().click();
  await page.getByRole('row', { name: 'ORCL Oracle Corporation NEW' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').fill('10');
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').fill('50');
  await page.locator('div').filter({ hasText: /^Stop value:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Stop value:$/ }).getByPlaceholder('value...').fill('100');
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').fill('1');
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').fill('40');
  await page.locator('div').filter({ hasText: /^Stop value:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Stop value:$/ }).getByPlaceholder('value...').fill('80');
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Orders').click();
  await page.getByText('Securities').first().click();
  await page.getByText('Forex').click();
  await page.getByRole('row', { name: 'NZD/HKD Oanda NZD/HKD OANDA:' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').fill('10');
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').fill('40');
  await page.locator('div').filter({ hasText: /^Stop value:$/ }).getByPlaceholder('value...').fill('50');
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Securities').first().click();
  await page.getByRole('row', { name: 'ORCL Oracle Corporation NEW' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').fill('1000');
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').fill('10000');
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').fill('50');
  await page.locator('div').filter({ hasText: /^Stop value:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Stop value:$/ }).getByPlaceholder('value...').fill('100');
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').click();
  await page.locator('div').filter({ hasText: /^Amount:$/ }).getByPlaceholder('value...').fill('100');
  await page.locator('div').filter({ hasText: /^Limit value:$/ }).getByPlaceholder('value...').fill('40');
  await page.locator('div').filter({ hasText: /^Stop value:$/ }).getByPlaceholder('value...').fill('80');
  await page.getByRole('button', { name: 'Buy' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Log out').click();
  await page.getByText('Employee').click();
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('ray@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('Dalio.0');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Securities').click();
  await page.getByText('Orders').click();
  await page.getByText('Requests').click();
  await page.getByRole('button', { name: 'Approve' }).first().click();
});